#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# if any param presents, just unset all proxies.
function proxy() {
  if [ $# -eq 0 ]; then
    export https_proxy=http://localhost:8123; export http_proxy=http://localhost:8123
  else
    echo "Proxy is unset."
    unset http_proxy https_proxy
  fi
}

# Customize to your needs...
if [[ `uname` == 'Linux' ]]
then
  alias ls="ls -Fh --color=auto"
  export no_proxy=raspberrypi.local
  export LS_COLORS="di=34:ln=35:so=32:pi=33:ex=31:bd=36;01:cd=33;01:su=31;40;07:sg=36;40;07:tw=32;40;07:ow=33;40;07:"
else
  alias ls="ls -GFh"

  # in Linux container, we have no macvim
  # use macvim as a whole
  MacVim=/Applications/MacVim.app/Contents/MacOS/Vim
  alias vim=$MacVim
  export VISUAL=$MacVim;EDITOR=$MacVim
  unset MacVim

  export GOROOT=/usr/local/opt/go/libexec
  export JAVA_HOME=`/usr/libexec/java_home`
  #export ANDROID_HOME=/usr/local/Cellar/android-sdk/24.4.1_1
  proxy
fi

export GOPATH=~
export LC_CTYPE=$LANG
export TERM=xterm-256color
export src=~/src/github.com/longkai
export PATH=~/bin:$GOROOT/bin:$PATH

alias vi="vim"
alias l="ls" 
alias ll="ls -l" 
alias la="ls -a"
alias grep="grep -i --color=auto"

bindkey "^P" up-line-or-search
bindkey "^N" down-line-or-search

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/runcoms/private" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/runcoms/private"
fi
